Update .gitignore
learningequality/sushi-chef-refugee-response-crisis-advice pull request #4
Opened 2020-05-22 00:17 UTC by WenyuZhang1992

2020-07-02 21:03 UTC, kollivier requested changes
This is awesome, thanks! This is a really well done chef, especially considering it's your first one! Most of the comments I made were around some conventions we use when coding, or are asking for clarification on a couple points. The only real blocker is that we do want the language to be set on each VideoNode, and we've just recently settled on a new convention for how we show the top level topics for multi-language channels. Once these changes are made and the channel on Studio is updated, I think this will be good to go from the tech perspective!

2020-07-02 21:03 UTC, kollivier commented on sushichef.py
> +          if key == NO_CACHE_KEYNAME:
One thing to be careful about is mixing two space and four space indents in your Python code. I'm guessing this is because your editor is configured for two spaces, but existing / template code is using four spaces. While Python allows you to do mix like this, it is best to choose either two or four space indents and use them consistently. Python code typically uses four space indents, so if you can configure your editor to do four spaces specifically for Python it may make it easier when working with other peoples' code, but we don't set a hard requirement on spacing in our scripts currently.

2020-07-02 21:03 UTC, kollivier commented on google_sheet_utils.py
> +        self.creds = pickle.load(token)
I would suggest putting this in a try / except block, so that if there's a failure to read the pickle file for any reason (e.g. corrupt file), the script will continue and just try to read the credentials file instead.

2020-07-02 21:03 UTC, kollivier commented on sushichef.py
> +import argparse
This is not a blocker to merging, but we tend to follow the convention of having imports in alphabetical order to make it easier to quickly look for a particular import.

2020-07-02 21:03 UTC, kollivier commented on sushichef.py
> +          #   LOGGER.info("Input language: '%s'", CHANNEL_LANGUAGE)
Unless you are planning to make this argument work in the future, you can just delete the commented code. This way future contributors aren't left wondering if this code is supposed to work but got disabled, or if it is old code that can be deleted.

2020-07-02 21:03 UTC, kollivier commented on sushichef.py
> -from ricecooker.config import LOGGER              # Use LOGGER to print messages
Out of curiosity, why did you switch from the ricecooker LOGGER to using logging directly?

2020-07-02 21:03 UTC, kollivier commented on sushichef.py
> +                      language='und'
Is this language property used anywhere? If not, can we remove the property?

2020-07-02 21:03 UTC, kollivier commented on sushichef.py
> +              language=lang_obj.code
We need to set the `VideoNode.language` property as well as `YouTubeVideoFile.language` for the node itself to get picked up as being in a certain language. Could you update this?

2020-07-02 21:03 UTC, kollivier commented on sushichef.py
> +          if key == EXTRACT_VIDEO_INFO:
It might be useful for people running this script in the future to document under what circumstances one would use the `--video` and `--playlist` options. It appears they are used to re-download or update specific videos before generating the channel?

Also, it seems they must be used in combination? If so, might want to add some error message if only `--playlist` is specified.

2020-07-02 21:03 UTC, kollivier commented on sushichef.py
> +              title=TOPIC_NAME_FORMAT.format(rr_lang_obj.name),
We just recently decided upon a convention for multi-language channels, where the top level topics use the language name as the title and nothing else. Could you update the code to set the title to just `title=rr_lang_obj.name`?

2020-07-03 00:07 UTC, WenyuZhang1992 commented on sushichef.py
> -from ricecooker.config import LOGGER              # Use LOGGER to print messages
I'm more familiar with the python logging package. But will see how to use ricecooker LOGGER for better code structure.

2020-07-04 16:48 UTC, kollivier approved these changes

2020-07-04 16:49 UTC, merged